import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { basename, extname, join, sep } from "node:path";
import type { Plugin } from "vite";
import { renderMarkdownFragment } from "./renderMarkdownFragment.ts";

const POSTS_DIR = "content/posts";
const ABOUT_ME_FILE = "content/about/me.md";
const PROJECTS_DIR = "content/about/projects";
const OUTPUT_DIR = "public/components";

interface Source {
  slug: string;
  filePath: string;
  eyebrow: string;
}

function slugFor(fileName: string): string {
  return basename(fileName, extname(fileName));
}

function collectSources(root: string): Source[] {
  const sources: Source[] = [];

  const postsDir = join(root, POSTS_DIR);
  if (existsSync(postsDir)) {
    for (const file of readdirSync(postsDir).filter((f) => f.endsWith(".md"))) {
      const slug = slugFor(file);
      sources.push({ slug, filePath: join(postsDir, file), eyebrow: `~/posts/${slug}.md` });
    }
  }

  const aboutMePath = join(root, ABOUT_ME_FILE);
  if (existsSync(aboutMePath)) {
    sources.push({ slug: "me", filePath: aboutMePath, eyebrow: "~/about/me.md" });
  }

  const projectsDir = join(root, PROJECTS_DIR);
  if (existsSync(projectsDir)) {
    for (const file of readdirSync(projectsDir).filter((f) => f.endsWith(".md"))) {
      const slug = slugFor(file);
      sources.push({ slug, filePath: join(projectsDir, file), eyebrow: `~/about/projects/${slug}.md` });
    }
  }

  return sources;
}

function assertNoSlugCollisions(sources: Source[]): void {
  const seen = new Map<string, string>();
  for (const source of sources) {
    const existing = seen.get(source.slug);
    if (existing) {
      throw new Error(
        `markdown-components: slug "${source.slug}" would be generated by both ${existing} and ` +
          `${source.filePath}. public/components/ is a flat namespace — rename one of these files.`,
      );
    }
    seen.set(source.slug, source.filePath);
  }
}

function buildOne(root: string, source: Source): void {
  const raw = readFileSync(source.filePath, "utf-8");
  const html = renderMarkdownFragment(raw, source.eyebrow);
  const outDir = join(root, OUTPUT_DIR);
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, `${source.slug}.html`), html);
}

function buildAll(root: string): Source[] {
  const sources = collectSources(root);
  assertNoSlugCollisions(sources);
  for (const source of sources) buildOne(root, source);
  return sources;
}

function isRelevantPath(root: string, file: string): boolean {
  const postsDir = join(root, POSTS_DIR) + sep;
  const projectsDir = join(root, PROJECTS_DIR) + sep;
  const aboutMePath = join(root, ABOUT_ME_FILE);
  return file.startsWith(postsDir) || file.startsWith(projectsDir) || file === aboutMePath;
}

export function markdownComponents(): Plugin {
  let root = process.cwd();

  return {
    name: "markdown-components",
    configResolved(config) {
      root = config.root;
    },
    buildStart() {
      buildAll(root);
    },
    configureServer(server) {
      server.watcher.add([join(root, POSTS_DIR), join(root, ABOUT_ME_FILE), join(root, PROJECTS_DIR)]);

      const regenerate = (file: string) => {
        if (!isRelevantPath(root, file)) return;
        try {
          buildAll(root);
        } catch (error) {
          server.config.logger.error(String(error));
        }
      };

      server.watcher.on("add", regenerate);
      server.watcher.on("change", regenerate);
      server.watcher.on("unlink", (file) => {
        if (!isRelevantPath(root, file)) return;
        try {
          const sources = buildAll(root);
          const slug = slugFor(basename(file));
          if (!sources.some((s) => s.slug === slug)) {
            const outPath = join(root, OUTPUT_DIR, `${slug}.html`);
            if (existsSync(outPath)) rmSync(outPath);
          }
        } catch (error) {
          server.config.logger.error(String(error));
        }
      });
    },
  };
}