import { describe, expect, it } from "vitest";
import { assertNoVirtualPathCollisions, collectFileSources, collectFolderSources } from "./collect.ts";

const CONTENT_DIR = new URL("../../../content", import.meta.url).pathname;

describe("collectFileSources", () => {
  it("collects posts, about/me.md, about/stack.json, and projects with virtual paths", () => {
    const sources = collectFileSources(CONTENT_DIR);

    expect(sources.some((s) => s.virtualPath === "/posts/typescript-notes.md" && s.kind === "markdown")).toBe(
      true,
    );
    expect(sources.some((s) => s.virtualPath === "/about/me.md" && s.kind === "markdown")).toBe(true);
    expect(sources.some((s) => s.virtualPath === "/about/stack.json" && s.kind === "json")).toBe(true);
    expect(
      sources.some((s) => s.virtualPath === "/about/projects/vespaiach.com.md" && s.kind === "markdown"),
    ).toBe(true);
    expect(sources.some((s) => s.virtualPath.startsWith("/topics"))).toBe(false);
    expect(sources.every((s) => s.type === "file")).toBe(true);
  });
});

describe("collectFolderSources", () => {
  it("builds a root listing of the three top-level folders", () => {
    const [root] = collectFolderSources(CONTENT_DIR);

    expect(root.virtualPath).toBe("/");
    expect(root.entries.map((e) => e.name)).toEqual(["about", "posts", "topics"]);
    expect(root.entries.every((e) => e.isDirectory)).toBe(true);
  });

  it("builds a /posts listing from post frontmatter", () => {
    const posts = collectFolderSources(CONTENT_DIR).find((s) => s.virtualPath === "/posts");

    expect(posts).toBeDefined();
    expect(posts?.entries.some((e) => e.name === "typescript-notes.md" && !e.isDirectory)).toBe(true);
  });

  it("derives a /topics listing from post tags", () => {
    const topics = collectFolderSources(CONTENT_DIR).find((s) => s.virtualPath === "/topics");

    expect(topics).toBeDefined();
    expect(topics?.entries.some((e) => e.name === "javascript" && e.isDirectory)).toBe(true);
  });

  it("builds an /about listing with files and a projects directory", () => {
    const about = collectFolderSources(CONTENT_DIR).find((s) => s.virtualPath === "/about");

    expect(about?.entries.map((e) => e.name).sort()).toEqual(["me.md", "projects", "stack.json"]);
    expect(about?.entries.find((e) => e.name === "projects")?.isDirectory).toBe(true);
  });

  it("builds an /about/projects listing from project files", () => {
    const projects = collectFolderSources(CONTENT_DIR).find((s) => s.virtualPath === "/about/projects");

    expect(projects?.entries.map((e) => e.name).sort()).toEqual(["app.junecare.co.md", "vespaiach.com.md"]);
    expect(projects?.entries.every((e) => !e.isDirectory)).toBe(true);
  });
});

describe("assertNoVirtualPathCollisions", () => {
  it("throws when duplicate virtual paths exist across sources", () => {
    const sources = [
      {
        type: "file" as const,
        virtualPath: "/posts/duplicate.md",
        filePath: "content/posts/duplicate.md",
        kind: "markdown" as const,
      },
      {
        type: "file" as const,
        virtualPath: "/posts/duplicate.md",
        filePath: "content/about/projects/duplicate.md",
        kind: "markdown" as const,
      },
    ];

    expect(() => assertNoVirtualPathCollisions(sources)).toThrow(
      /virtual path "\/posts\/duplicate\.md" would be generated by both/,
    );
  });
});