import { describe, expect, it } from "vitest";
import { assertNoVirtualPathCollisions, collectFileSources, collectFolderSources } from "./collect.ts";

const CONTENT_DIR = new URL("../../content", import.meta.url).pathname;

describe("collectFileSources", () => {
  it("collects posts, about/me.md, about/stack.json, and projects with virtual paths", () => {
    const sources = collectFileSources(CONTENT_DIR);

    expect(sources.some((s) => s.virtualPath === "/posts/typescript-notes.md" && s.kind === "markdown")).toBe(
      true,
    );
    expect(sources.some((s) => s.virtualPath === "/about/me.md" && s.kind === "markdown")).toBe(true);
    expect(sources.some((s) => s.virtualPath === "/about/stack.json" && s.kind === "json")).toBe(true);
    expect(
      sources.some((s) => s.virtualPath === "/about/projects/vespaiach.com.md" && s.kind === "markdown"),
    ).toBe(true);
    expect(sources.some((s) => s.virtualPath.startsWith("/topics"))).toBe(false);
    expect(sources.every((s) => s.type === "file")).toBe(true);
  });
});

describe("collectFolderSources", () => {
  it("builds a root listing of the three top-level folders", () => {
    const [root] = collectFolderSources(CONTENT_DIR);

    expect(root.virtualPath).toBe("/");
    expect(root.entries.map((e) => e.name)).toEqual(["about", "posts", "topics"]);
    expect(root.entries.every((e) => e.isDirectory)).toBe(true);
  });

  it("builds a /posts listing from post frontmatter", () => {
    const posts = collectFolderSources(CONTENT_DIR).find((s) => s.virtualPath === "/posts");

    expect(posts).toBeDefined();
    expect(posts?.entries.some((e) => e.name === "typescript-notes.md" && !e.isDirectory)).toBe(true);
  });

  it("derives a /topics listing from post tags", () => {
    const topics = collectFolderSources(CONTENT_DIR).find((s) => s.virtualPath === "/topics");

    expect(topics).toBeDefined();
    expect(topics?.entries.some((e) => e.name === "javascript" && e.isDirectory)).toBe(true);
  });

  it("shows how many posts each topic has in the size column", () => {
    const topics = collectFolderSources(CONTENT_DIR).find((s) => s.virtualPath === "/topics");

    expect(topics?.entries.find((e) => e.name === "javascript")?.size).toBe("3 posts");
    expect(topics?.entries.find((e) => e.name === "dns")?.size).toBe("1 post");
  });

  it("builds one /topics/<tag> listing per tag with symlinks to the tagged posts", () => {
    const javascript = collectFolderSources(CONTENT_DIR).find((s) => s.virtualPath === "/topics/javascript");

    expect(javascript?.entries.map((e) => e.name)).toEqual([
      "working-with-javascript-date-object.md",
      "javascript-interesting-things.md",
      "discard-after-usages.md",
    ]);
    expect(javascript?.entries.every((e) => !e.isDirectory)).toBe(true);
    expect(javascript?.entries[0]).toMatchObject({
      linkTarget: "../../posts/working-with-javascript-date-object.md",
      size: "1 min",
      isoDate: "2022-06-20T00:00:00.000Z",
    });
  });

  it("names topics after their tags with whitespace replaced so they can be typed as a path", () => {
    const folders = collectFolderSources(CONTENT_DIR);
    const topics = folders.find((s) => s.virtualPath === "/topics");

    expect(topics?.entries.some((e) => e.name === "syntax-highlight")).toBe(true);
    expect(topics?.entries.some((e) => e.name.includes(" "))).toBe(false);
    expect(folders.some((s) => s.virtualPath === "/topics/syntax-highlight")).toBe(true);
  });

  it("builds an /about listing with files and a projects directory", () => {
    const about = collectFolderSources(CONTENT_DIR).find((s) => s.virtualPath === "/about");

    expect(about?.entries.map((e) => e.name).sort()).toEqual([
      "me.md",
      "projects",
      "resume.md",
      "stack.json",
    ]);
    expect(about?.entries.find((e) => e.name === "projects")?.isDirectory).toBe(true);
  });

  it("builds an /about/projects listing from project files", () => {
    const projects = collectFolderSources(CONTENT_DIR).find((s) => s.virtualPath === "/about/projects");

    expect(projects?.entries.map((e) => e.name).sort()).toEqual(["app.junecare.co.md", "vespaiach.com.md"]);
    expect(projects?.entries.every((e) => !e.isDirectory)).toBe(true);
  });
});

describe("assertNoVirtualPathCollisions", () => {
  it("throws when duplicate virtual paths exist across sources", () => {
    const sources = [
      {
        type: "file" as const,
        virtualPath: "/posts/duplicate.md",
        filePath: "content/posts/duplicate.md",
        kind: "markdown" as const,
      },
      {
        type: "file" as const,
        virtualPath: "/posts/duplicate.md",
        filePath: "content/about/projects/duplicate.md",
        kind: "markdown" as const,
      },
    ];

    expect(() => assertNoVirtualPathCollisions(sources)).toThrow(
      /virtual path "\/posts\/duplicate\.md" would be generated by both/,
    );
  });
});