import { randomUUID } from "node:crypto";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { renderJsonView, renderMarkdownView } from "../lib/markedFragment.ts";
import {
  assertNoVirtualPathCollisions,
  collectFileSources,
  collectFolderSources,
  type Source,
} from "./collect.ts";
import { HOME_META, metaFor } from "./pageMeta.ts";
import { pageUrl } from "./renderHead.ts";
import { renderListingView } from "./renderListingView.ts";
import { type Page, pagePathFor, renderPage } from "./renderPage.ts";
import { renderResumeView } from "./renderResumeView.ts";
import { renderSitemap } from "./renderSitemap.ts";
import { renderTreeView } from "./renderTreeView.ts";

const HOME_PAGE_PATH = "index.html";

function commandFor(source: Source): string {
  return source.type === "folder" ? "ls" : "cat";
}

async function renderSource(source: Source): Promise<string> {
  if (source.type === "folder") return renderListingView(source.virtualPath, source.entries);

  const raw = readFileSync(source.filePath, "utf-8");
  const eyebrow = `~${source.virtualPath}`;
  if (source.kind === "json") return await renderJsonView(raw, eyebrow);
  if (source.kind === "resume") return renderResumeView(raw, eyebrow, pageUrl(pagePathFor(source)));
  return await renderMarkdownView(raw, eyebrow, pageUrl(pagePathFor(source)));
}

function writeView(outputDir: string, html: string): string {
  const fileName = `${randomUUID()}.html`;
  writeFileSync(join(outputDir, fileName), html);
  return `/generated/${fileName}`;
}

function writePage(pagesDir: string, template: string, page: Page): void {
  const filePath = join(pagesDir, page.pagePath);
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, renderPage(template, page));
}

export async function generateViews(root: string): Promise<Record<string, string>> {
  const contentDir = join(root, "content");
  const folderSources = collectFolderSources(contentDir);
  const sources: Source[] = [...collectFileSources(contentDir), ...folderSources];
  assertNoVirtualPathCollisions(sources);

  const outputDir = join(root, "dist", "generated");
  rmSync(outputDir, { recursive: true, force: true });
  mkdirSync(outputDir, { recursive: true });

  const manifest: Record<string, string> = {};
  const pages: Page[] = [];

  for (const source of sources) {
    const command = `${commandFor(source)} ${source.virtualPath}`;
    const viewHtml = await renderSource(source);
    manifest[command] = writeView(outputDir, viewHtml);

    if (source.virtualPath === "/") continue;

    const page: Page = {
      ...metaFor(source),
      pagePath: pagePathFor(source),
      active: source.virtualPath.split("/")[1],
      command,
      viewHtml,
    };
    if (source.virtualPath === "/posts") {
      pages.push(
        { ...page, canonicalPath: HOME_PAGE_PATH },
        { ...page, ...HOME_META, pagePath: HOME_PAGE_PATH },
      );
    } else {
      pages.push(page);
    }
  }

  for (const folder of folderSources) {
    manifest[`tree ${folder.virtualPath}`] = writeView(
      outputDir,
      renderTreeView(folderSources, folder.virtualPath),
    );
  }

  const template = readFileSync(join(root, "index.html"), "utf-8");
  const pagesDir = join(root, "pages");
  rmSync(pagesDir, { recursive: true, force: true });

  const writtenPagePaths = new Set<string>();
  for (const page of pages) {
    if (writtenPagePaths.has(page.pagePath)) {
      throw new Error(`content-views: page "${page.pagePath}" would be generated by more than one view.`);
    }
    writtenPagePaths.add(page.pagePath);
    writePage(pagesDir, template, page);
  }

  const publicDir = join(root, "public");
  mkdirSync(publicDir, { recursive: true });
  writeFileSync(
    join(publicDir, "sitemap.xml"),
    renderSitemap(
      pages
        .filter((page) => !page.canonicalPath)
        .map((page) => ({ url: pageUrl(page.pagePath), lastmod: page.article?.modified.slice(0, 10) })),
    ),
  );

  const sortedManifest = Object.fromEntries(
    Object.entries(manifest).sort(([left], [right]) => left.localeCompare(right)),
  );
  const srcDir = join(root, "src");
  mkdirSync(srcDir, { recursive: true });
  writeFileSync(join(srcDir, "manifest.json"), `${JSON.stringify(sortedManifest, null, 2)}\n`);

  return sortedManifest;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await generateViews(process.cwd());
}