import { randomUUID } from "node:crypto";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { extname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { renderJsonView, renderMarkdownView } from "../lib/markedFragment.ts";

export type ContentKind = "markdown" | "json";

export interface ContentSource {
  virtualPath: string;
  filePath: string;
  kind: ContentKind;
}

function kindFor(filePath: string): ContentKind {
  return extname(filePath) === ".json" ? "json" : "markdown";
}

export function collectContentSources(contentDir: string): ContentSource[] {
  const sources: ContentSource[] = [];

  const postsDir = join(contentDir, "posts");
  if (existsSync(postsDir)) {
    for (const file of readdirSync(postsDir).filter((f) => f.endsWith(".md"))) {
      const filePath = join(postsDir, file);
      sources.push({ virtualPath: `/posts/${file}`, filePath, kind: kindFor(filePath) });
    }
  }

  const aboutMePath = join(contentDir, "about", "me.md");
  if (existsSync(aboutMePath)) {
    sources.push({ virtualPath: "/about/me.md", filePath: aboutMePath, kind: kindFor(aboutMePath) });
  }

  const stackJsonPath = join(contentDir, "about", "stack.json");
  if (existsSync(stackJsonPath)) {
    sources.push({ virtualPath: "/about/stack.json", filePath: stackJsonPath, kind: kindFor(stackJsonPath) });
  }

  const projectsDir = join(contentDir, "about", "projects");
  if (existsSync(projectsDir)) {
    for (const file of readdirSync(projectsDir).filter((f) => f.endsWith(".md"))) {
      const filePath = join(projectsDir, file);
      sources.push({
        virtualPath: `/about/projects/${file}`,
        filePath,
        kind: kindFor(filePath),
      });
    }
  }

  return sources.sort((left, right) => left.virtualPath.localeCompare(right.virtualPath));
}

export function assertNoVirtualPathCollisions(sources: ContentSource[]): void {
  const seen = new Map<string, string>();
  for (const source of sources) {
    const existing = seen.get(source.virtualPath);
    if (existing) {
      throw new Error(
        `content-views: virtual path "${source.virtualPath}" would be generated by both ${existing} and ` +
          `${source.filePath}.`,
      );
    }
    seen.set(source.virtualPath, source.filePath);
  }
}

export async function generateContentViews(root: string): Promise<Record<string, string>> {
  const sources = collectContentSources(join(root, "content"));
  assertNoVirtualPathCollisions(sources);

  const outputDir = join(root, "dist", "generated");
  rmSync(outputDir, { recursive: true, force: true });
  mkdirSync(outputDir, { recursive: true });

  const manifest: Record<string, string> = {};

  for (const source of sources) {
    const raw = readFileSync(source.filePath, "utf-8");
    const eyebrow = `~${source.virtualPath}`;
    const html =
      source.kind === "json" ? await renderJsonView(raw, eyebrow) : await renderMarkdownView(raw, eyebrow);

    const fileName = `${randomUUID()}.html`;
    writeFileSync(join(outputDir, fileName), html);
    manifest[source.virtualPath] = `/generated/${fileName}`;
  }

  const sortedManifest = Object.fromEntries(
    Object.entries(manifest).sort(([left], [right]) => left.localeCompare(right)),
  );
  const srcDir = join(root, "src");
  mkdirSync(srcDir, { recursive: true });
  writeFileSync(join(srcDir, "manifest.json"), `${JSON.stringify(sortedManifest, null, 2)}\n`);

  return sortedManifest;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await generateContentViews(process.cwd());
}