import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync, symlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import {
  assertNoVirtualPathCollisions,
  collectContentSources,
  generateContentViews,
} from "./content-views.ts";

const CONTENT_DIR = new URL("../../content", import.meta.url).pathname;
const temporaryRoots: string[] = [];

function createRoot(): string {
  const root = mkdtempSync(join(tmpdir(), "content-views-"));
  symlinkSync(CONTENT_DIR, join(root, "content"));
  temporaryRoots.push(root);
  return root;
}

afterEach(() => {
  for (const root of temporaryRoots.splice(0)) rmSync(root, { force: true, recursive: true });
});

describe("collectContentSources", () => {
  it("collects posts, about/me.md, about/stack.json, and projects with virtual paths", () => {
    const sources = collectContentSources(CONTENT_DIR);

    expect(sources.some((s) => s.virtualPath === "/posts/typescript-notes.md" && s.kind === "markdown")).toBe(
      true,
    );
    expect(sources.some((s) => s.virtualPath === "/about/me.md" && s.kind === "markdown")).toBe(true);
    expect(sources.some((s) => s.virtualPath === "/about/stack.json" && s.kind === "json")).toBe(true);
    expect(
      sources.some((s) => s.virtualPath === "/about/projects/vespaiach.com.md" && s.kind === "markdown"),
    ).toBe(true);
    expect(sources.some((s) => s.virtualPath.startsWith("/topics"))).toBe(false);
  });
});

describe("assertNoVirtualPathCollisions", () => {
  it("throws when duplicate virtual paths exist across sources", () => {
    const sources = [
      {
        virtualPath: "/posts/duplicate.md",
        filePath: "content/posts/duplicate.md",
        kind: "markdown" as const,
      },
      {
        virtualPath: "/posts/duplicate.md",
        filePath: "content/about/projects/duplicate.md",
        kind: "markdown" as const,
      },
    ];

    expect(() => assertNoVirtualPathCollisions(sources)).toThrow(
      /virtual path "\/posts\/duplicate\.md" would be generated by both/,
    );
  });
});

describe("generateContentViews", () => {
  it("writes uuid-named fragments to dist/generated and a matching src/manifest.json", async () => {
    const root = createRoot();

    const manifest = await generateContentViews(root);

    const sourceCount = collectContentSources(join(root, "content")).length;
    expect(Object.keys(manifest)).toHaveLength(sourceCount);

    const uuidPathPattern = /^\/generated\/[0-9a-f-]{36}\.html$/;
    for (const value of Object.values(manifest)) {
      expect(value).toMatch(uuidPathPattern);
    }

    const manifestOnDisk = JSON.parse(readFileSync(join(root, "src", "manifest.json"), "utf-8"));
    expect(manifestOnDisk).toEqual(manifest);

    const postFileName = manifest["/posts/typescript-notes.md"].replace("/generated/", "");
    const postPath = join(root, "dist", "generated", postFileName);
    expect(existsSync(postPath)).toBe(true);
    const postContent = readFileSync(postPath, "utf-8");
    expect(postContent).toContain("<article");
    expect(postContent).toContain("~/posts/typescript-notes.md");

    const stackFileName = manifest["/about/stack.json"].replace("/generated/", "");
    const stackContent = readFileSync(join(root, "dist", "generated", stackFileName), "utf-8");
    expect(stackContent).toContain("data-code-block");
    expect(stackContent).toContain("languages");
  });

  it("clears stale files from a previous run instead of accumulating them", async () => {
    const root = createRoot();

    await generateContentViews(root);
    const outputDir = join(root, "dist", "generated");
    const firstRunFiles = readdirSync(outputDir);

    const secondManifest = await generateContentViews(root);
    const secondRunFiles = readdirSync(outputDir);

    expect(secondRunFiles).toHaveLength(firstRunFiles.length);
    expect(secondRunFiles.every((f) => Object.values(secondManifest).includes(`/generated/${f}`))).toBe(true);
  });
});