import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, extname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { renderMarkdownFragment } from "../lib/renderMarkdownFragment.ts";

export interface MarkdownViewSource {
  slug: string;
  filePath: string;
  eyebrow: string;
}

function slugFor(fileName: string): string {
  return basename(fileName, extname(fileName));
}

export function collectMarkdownSources(contentDir: string): MarkdownViewSource[] {
  const sources: MarkdownViewSource[] = [];

  const postsDir = join(contentDir, "posts");
  if (existsSync(postsDir)) {
    for (const file of readdirSync(postsDir).filter((f) => f.endsWith(".md"))) {
      const slug = slugFor(file);
      sources.push({ slug, filePath: join(postsDir, file), eyebrow: `~/posts/${slug}.md` });
    }
  }

  const aboutMePath = join(contentDir, "about", "me.md");
  if (existsSync(aboutMePath)) {
    sources.push({ slug: "me", filePath: aboutMePath, eyebrow: "~/about/me.md" });
  }

  const projectsDir = join(contentDir, "about", "projects");
  if (existsSync(projectsDir)) {
    for (const file of readdirSync(projectsDir).filter((f) => f.endsWith(".md"))) {
      const slug = slugFor(file);
      sources.push({ slug, filePath: join(projectsDir, file), eyebrow: `~/about/projects/${slug}.md` });
    }
  }

  return sources.sort((left, right) => left.slug.localeCompare(right.slug));
}

export function assertNoSlugCollisions(sources: MarkdownViewSource[]): void {
  const seen = new Map<string, string>();
  for (const source of sources) {
    const existing = seen.get(source.slug);
    if (existing) {
      throw new Error(
        `markdown-views: slug "${source.slug}" would be generated by both ${existing} and ` +
          `${source.filePath}. src/generated/ is a flat namespace — rename one of these files.`,
      );
    }
    seen.set(source.slug, source.filePath);
  }
}

export function generateMarkdownViews(root: string): MarkdownViewSource[] {
  const sources = collectMarkdownSources(join(root, "content"));
  assertNoSlugCollisions(sources);

  const outputDir = join(root, "src", "generated");
  mkdirSync(outputDir, { recursive: true });

  for (const source of sources) {
    const raw = readFileSync(source.filePath, "utf-8");
    const html = renderMarkdownFragment(raw, source.eyebrow);
    writeFileSync(join(outputDir, `${source.slug}-view.html`), html);
  }

  return sources;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  generateMarkdownViews(process.cwd());
}