import { existsSync, mkdtempSync, readFileSync, rmSync, symlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { assertNoSlugCollisions, collectMarkdownSources, generateMarkdownViews } from "./markdown-views.ts";

const CONTENT_DIR = new URL("../../content", import.meta.url).pathname;
const temporaryRoots: string[] = [];

function createRoot(): string {
  const root = mkdtempSync(join(tmpdir(), "markdown-views-"));
  symlinkSync(CONTENT_DIR, join(root, "content"));
  temporaryRoots.push(root);
  return root;
}

afterEach(() => {
  for (const root of temporaryRoots.splice(0)) rmSync(root, { force: true, recursive: true });
});

describe("collectMarkdownSources", () => {
  it("collects posts, about/me, and projects with correct eyebrows", () => {
    const sources = collectMarkdownSources(CONTENT_DIR);

    expect(sources.some((s) => s.slug === "me" && s.eyebrow === "~/about/me.md")).toBe(true);
    expect(
      sources.some(
        (s) => s.slug === "app.junecare.co" && s.eyebrow === "~/about/projects/app.junecare.co.md",
      ),
    ).toBe(true);
    expect(
      sources.some((s) => s.slug === "typescript-notes" && s.eyebrow === "~/posts/typescript-notes.md"),
    ).toBe(true);
  });
});

describe("assertNoSlugCollisions", () => {
  it("throws when duplicate slugs exist across sources", () => {
    const sources = [
      { slug: "duplicate", filePath: "content/posts/duplicate.md", eyebrow: "~/posts/duplicate.md" },
      {
        slug: "duplicate",
        filePath: "content/about/projects/duplicate.md",
        eyebrow: "~/about/projects/duplicate.md",
      },
    ];

    expect(() => assertNoSlugCollisions(sources)).toThrow(/slug "duplicate" would be generated by both/);
  });
});

describe("generateMarkdownViews", () => {
  it("writes rendered markdown fragments with -view.html suffix into src/generated", () => {
    const root = createRoot();

    const sources = generateMarkdownViews(root);

    expect(sources.length).toBeGreaterThan(0);
    const meViewPath = join(root, "src", "generated", "me-view.html");
    expect(existsSync(meViewPath)).toBe(true);

    const meContent = readFileSync(meViewPath, "utf-8");
    expect(meContent).toContain("~/about/me.md");
    expect(meContent).toContain("<article");

    const postViewPath = join(root, "src", "generated", "typescript-notes-view.html");
    expect(existsSync(postViewPath)).toBe(true);

    const postContent = readFileSync(postViewPath, "utf-8");
    expect(postContent).toContain("~/posts/typescript-notes.md");
    expect(postContent).toContain("<article");
  });
});